name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-syntax-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make test script executable
        run: chmod +x tests/run_syntax_tests.sh

      - name: Build lexer and parser
        working-directory: utils
        run: |
          make clean
          make

      - name: Build test harness
        working-directory: tests
        run: |
          make clean
          make

      - name: Run tests
        working-directory: tests
        run: ./run_syntax_tests.sh
